// Generated by scripts/generate_project_pages.py.
window.LAV_PROJECT_PAGES = [
  {
    "category": "interior",
    "image": "/images/portfolio-hire/interior-02.webp",
    "mobileImage": "/images/portfolio-hire/interior-02-mobile.webp",
    "width": 1448,
    "type": "Жилая квартира · Москва",
    "title": "Warm Classic Apartment",
    "description": "Светлый семейный интерьер, где мягкая классическая архитектура соединяется с современной мебелью, тёплой пудровой палитрой и деликатными латунными акцентами.",
    "tags": [
      "Жилой интерьер",
      "Концепция",
      "Комплектация"
    ],
    "url": "/interior/projects/warm-classic-apartment/"
  },
  {
    "category": "interior",
    "image": "/images/projects/ivory-marble/01-kitchen.webp",
    "mobileImage": "/images/projects/ivory-marble/01-kitchen-mobile.webp",
    "width": 1080,
    "type": "Жилая квартира",
    "title": "Ivory Marble",
    "description": "Светлый интерьер в современной классике, построенный на выразительном рисунке мрамора, тонких латунных акцентах и мягкой пластике мебели. Единая палитра связывает кухню, гостиную, кабинет, спальню и ванную комнату в цельное пространство.",
    "tags": [
      "Мрамор",
      "Латунь",
      "Современная классика"
    ],
    "url": "/interior/projects/ivory-marble/"
  }
];
