#!/usr/bin/env python3
"""Generate indexable project pages from interior/projects/projects.json."""

from __future__ import annotations

import html
import json
import re
import shutil
import sys
from pathlib import Path
from string import Template


ROOT = Path(__file__).resolve().parents[1]
PROJECTS_DIR = ROOT / "interior" / "projects"
DATA_FILE = PROJECTS_DIR / "projects.json"
TEMPLATE_FILE = PROJECTS_DIR / "project-template.html"
GENERATED_MARKER = "<!-- Generated by scripts/generate_project_pages.py. Do not edit this file directly. -->\n"
SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def load_catalog() -> tuple[dict, list[dict]]:
    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    projects = data.get("projects", [])
    if not isinstance(projects, list):
        raise ValueError("projects must be an array")
    slugs: set[str] = set()
    for index, project in enumerate(projects, 1):
        if not project.get("published", False):
            continue
        missing = [key for key in ("name", "slug", "description", "seoTitle", "seoDescription", "images") if not project.get(key)]
        if missing:
            raise ValueError(f"Project #{index} is missing: {', '.join(missing)}")
        slug = project["slug"]
        if not SLUG_PATTERN.fullmatch(slug):
            raise ValueError(f"Invalid slug '{slug}'. Use lowercase latin letters, numbers and hyphens.")
        if slug in slugs:
            raise ValueError(f"Duplicate slug '{slug}'")
        slugs.add(slug)
        for image_index, image in enumerate(project["images"], 1):
            for key in ("src", "width", "height", "alt"):
                if not image.get(key):
                    raise ValueError(f"{slug}: image #{image_index} is missing '{key}'")
            source = ROOT / image["src"].lstrip("/")
            if not source.is_file():
                raise ValueError(f"{slug}: image does not exist: {image['src']}")
            mobile = image.get("mobileSrc")
            if mobile and not (ROOT / mobile.lstrip("/")).is_file():
                raise ValueError(f"{slug}: mobile image does not exist: {mobile}")
    return data, [project for project in projects if project.get("published", False)]


def picture_markup(image: dict, index: int) -> str:
    loading = 'fetchpriority="high"' if index == 0 else 'loading="lazy"'
    mobile = image.get("mobileSrc")
    source = f'<source media="(max-width: 720px)" srcset="{esc(mobile)}"/>' if mobile else ""
    layout = image.get("layout", "standard")
    if layout not in {"standard", "wide", "portrait"}:
        layout = "standard"
    return f'''<figure class="gallery-item {layout}">
          <picture>{source}<img src="{esc(image['src'])}" width="{int(image['width'])}" height="{int(image['height'])}" alt="{esc(image['alt'])}" {loading} decoding="async"/></picture>
          <button type="button" data-gallery-open data-full-src="{esc(image['src'])}" data-alt="{esc(image['alt'])}" aria-label="Открыть изображение {index + 1}: {esc(image['alt'])}"></button>
          <span class="gallery-index">{index + 1:02d} / {{total:02d}}</span>
        </figure>'''


def facts_markup(project: dict) -> str:
    facts = (("Тип", project.get("roomType")), ("Стиль", project.get("style")), ("Локация", project.get("location")))
    return "".join(f"<div><dt>{esc(label)}</dt><dd>{esc(value)}</dd></div>" for label, value in facts if value)


def project_link(project: dict | None, direction: str) -> str:
    if not project:
        return '<span class="pagination-placeholder" aria-hidden="true"></span>'
    label = "Previous Project" if direction == "previous" else "Next Project"
    arrow = "←" if direction == "previous" else "→"
    css_class = "pagination-link" if direction == "previous" else "pagination-link next"
    return f'<a class="{css_class}" href="/interior/projects/{esc(project["slug"])}/"><small>{arrow} {label}</small><strong>{esc(project["name"])}</strong></a>'


def related_markup(project: dict, projects: list[dict]) -> str:
    explicit = project.get("related", [])
    lookup = {item["slug"]: item for item in projects}
    related = [lookup[slug] for slug in explicit if slug in lookup and slug != project["slug"]]
    if len(related) < 3:
        candidates = [item for item in projects if item["slug"] != project["slug"] and item not in related]
        candidates.sort(key=lambda item: item.get("category") != project.get("category"))
        related.extend(candidates[: 3 - len(related)])
    cards = []
    for item in related[:3]:
        cover = item["images"][0]
        cards.append(f'''<a class="related-card" href="/interior/projects/{esc(item['slug'])}/">
              <img src="{esc(cover['src'])}" width="{int(cover['width'])}" height="{int(cover['height'])}" alt="{esc(cover['alt'])}" loading="lazy" decoding="async"/>
              <div class="related-copy"><small>{esc(item.get('roomType', 'Project'))}</small><h3>{esc(item['name'])}</h3></div>
            </a>''')
    if not cards:
        cover = project["images"][min(1, len(project["images"]) - 1)]
        cards.append(f'''<a class="related-card portfolio-card" href="/interior/#projects">
              <img src="{esc(cover['src'])}" width="{int(cover['width'])}" height="{int(cover['height'])}" alt="" loading="lazy" decoding="async"/>
              <div class="related-copy"><small>Interior · Exterior · Commercial</small><h3>Explore all projects</h3></div>
            </a>''')
    return "\n".join(cards)


def structured_data(site_url: str, project: dict, canonical: str, cover_url: str) -> str:
    payload = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "CreativeWork",
                "name": project["name"],
                "description": project["seoDescription"],
                "url": canonical,
                "image": [site_url.rstrip("/") + image["src"] for image in project["images"]],
                "creator": {"@type": "Person", "name": "Анжелика Лапихина"},
                "publisher": {"@type": "Organization", "name": "LAV Interiors", "url": site_url.rstrip("/") + "/"},
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Interior", "item": site_url.rstrip("/") + "/interior/"},
                    {"@type": "ListItem", "position": 2, "name": "Projects", "item": site_url.rstrip("/") + "/interior/#projects"},
                    {"@type": "ListItem", "position": 3, "name": project["name"], "item": canonical},
                ],
            },
        ],
    }
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def build_page(template: Template, site_url: str, project: dict, projects: list[dict], index: int) -> str:
    canonical = f"{site_url.rstrip('/')}/interior/projects/{project['slug']}/"
    cover = project["images"][0]
    gallery = "\n".join(picture_markup(image, image_index) for image_index, image in enumerate(project["images"]))
    gallery = gallery.replace("{total:02d}", f"{len(project['images']):02d}")
    previous = projects[index - 1] if index > 0 else None
    next_project = projects[index + 1] if index + 1 < len(projects) else None
    values = {
        "seo_title": esc(project["seoTitle"]),
        "seo_description": esc(project["seoDescription"]),
        "canonical_url": esc(canonical),
        "og_image": esc(site_url.rstrip("/") + cover["src"]),
        "og_image_alt": esc(cover["alt"]),
        "og_image_width": int(cover["width"]),
        "og_image_height": int(cover["height"]),
        "structured_data": structured_data(site_url, project, canonical, site_url.rstrip("/") + cover["src"]),
        "project_name": esc(project["name"]),
        "project_number": f"{index + 1:02d}",
        "project_description": esc(project["description"]),
        "project_facts": facts_markup(project),
        "gallery_items": gallery,
        "previous_project": project_link(previous, "previous"),
        "next_project": project_link(next_project, "next"),
        "related_projects": related_markup(project, projects),
    }
    return GENERATED_MARKER + template.safe_substitute(values)


def write_catalog_js(projects: list[dict]) -> None:
    catalog = []
    for project in projects:
        cover = project["images"][0]
        catalog.append({
            "category": project.get("category", "interior"),
            "image": cover["src"],
            "mobileImage": cover.get("mobileSrc", cover["src"]),
            "width": cover["width"],
            "type": " · ".join(value for value in (project.get("roomType"), project.get("location")) if value),
            "title": project["name"],
            "description": project["description"],
            "tags": project.get("tags", []),
            "url": f"/interior/projects/{project['slug']}/",
        })
    content = "// Generated by scripts/generate_project_pages.py.\nwindow.LAV_PROJECT_PAGES = " + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n"
    (PROJECTS_DIR / "catalog.js").write_text(content, encoding="utf-8")


def write_sitemap(site_url: str, projects: list[dict]) -> None:
    urls = ["/", "/interior/", "/portfolio/"] + [f"/interior/projects/{project['slug']}/" for project in projects]
    rows = "\n".join(f"  <url><loc>{esc(site_url.rstrip('/') + path)}</loc></url>" for path in urls)
    sitemap = f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{rows}\n</urlset>\n'
    (ROOT / "sitemap.xml").write_text(sitemap, encoding="utf-8")


def main() -> int:
    data, projects = load_catalog()
    if not projects:
        raise ValueError("At least one published project is required")
    template = Template(TEMPLATE_FILE.read_text(encoding="utf-8"))
    published_slugs = {project["slug"] for project in projects}
    for child in PROJECTS_DIR.iterdir():
        generated_file = child / "index.html"
        if child.is_dir() and child.name not in published_slugs and generated_file.is_file():
            first_line = generated_file.read_text(encoding="utf-8", errors="ignore").splitlines()[0]
            if first_line in GENERATED_MARKER:
                shutil.rmtree(child)
    for index, project in enumerate(projects):
        output_dir = PROJECTS_DIR / project["slug"]
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "index.html").write_text(build_page(template, data["siteUrl"], project, projects, index), encoding="utf-8")
    write_catalog_js(projects)
    write_sitemap(data["siteUrl"], projects)
    print(f"Generated {len(projects)} project page(s): {', '.join(sorted(published_slugs))}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Project generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
